name: Trivy

on:
  workflow_dispatch:

env:
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY: ascheid/trivy-test

permissions:
  contents: write
  actions: read
  security-events: write

jobs:
  trivy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [one, two]
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Build container
        working-directory: ./images/${{ matrix.image }}
        run: |
          docker build \
            --build-arg git_sha=$GITHUB_SHA \
            -t ${{ env.REGISTRY }}/${{ matrix.image }}:$GITHUB_SHA \
            -t ${{ env.REGISTRY }}/${{ matrix.image }}:latest .
      
      - name: Docker scan and SBOM to GitHub
        uses: ./.github/actions/docker-scan
        with:
          docker_image: ${{ env.REGISTRY }}/${{ matrix.image }}:latest
          token: ${{ secrets.GITHUB_TOKEN }}