name: Trivy

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY: ascheid/trivy-test

permissions:
  contents: write
  actions: read
  security-events: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # tag=v2.5.0

      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # tag=v2.11.1
        id: filter
        with:
          filters: |
            images/one: 'images/one/**'
            images/two: 'images/two/**'

  trivy:
    if: needs.changes.outputs.images != '[]'
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.changes.outputs.images) }}
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Build container
        working-directory: ${{ matrix.image }}
        run: |
          docker build \
            --build-arg git_sha=$GITHUB_SHA \
            -t ${{ env.REGISTRY }}/${{ matrix.image }}:$GITHUB_SHA \
            -t ${{ env.REGISTRY }}/${{ matrix.image }}:latest .
      
      - name: Docker scan and SBOM to GitHub
        uses: ./.github/actions/docker-scan
        with:
          docker_image: ${{ env.REGISTRY }}/${{ matrix.image }}:latest
          token: ${{ secrets.GITHUB_TOKEN }}
          