name: Trivy

on:
  workflow_dispatch:

env:
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY: ascheid/trivy-test

permissions:
  contents: write
  actions: read
  security-events: write

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Build container
        working-directory: ./
        run: |
          docker build \
            --build-arg git_sha=$GITHUB_SHA \
            -t $REGISTRY:$GITHUB_SHA \
            -t $REGISTRY:latest .
      
      - name: Docker scan and SBOM to GitHub
        uses: cds-snc/security-tools/.github/actions/docker-scan@e8bfe289161e1a923f8bb153c57280abfa33eb22
        with:
          docker_image: ${{ env.REGISTRY }}:${{ env.GITHUB_SHA }}
          token: ${{ secrets.GITHUB_TOKEN }}